// Base de datos de Maestros
// Aquí actualizan los nombres de los maestros cada ciclo
const teachersDB = {
    "Primer": { "A": "Nombre Docente 1A", "B": "Nombre Docente 1B" },
    "Segundo": { "A": "Nombre Docente 2A", "B": "Nombre Docente 2B" },
    "Tercer": { "A": "Nombre Docente 3A", "B": "Nombre Docente 3B" },
    "Cuarto": { "A": "Nombre Docente 4A", "B": "Nombre Docente 4B" },
    "Quinto": { "A": "Nombre Docente 5A", "B": "Nombre Docente 5B" },
    "Sexto": { "A": "Nombre Docente 6A", "B": "Nombre Docente 6B" }
};

// Base de datos de Alumnos
// Aquí pegan o actualizan las listas de los niños
const studentsDB = {
    "Primer": {
        "A": [
            "ANGELES LICONA ANA VICTORIA", "ARISTA SAGAHON LEILANI GISELLE", "BAUTISTA RODRÍGUEZ ESTEFANNY CAROLINA", 
            "DOMINGUEZ RODRÍGUEZ DYLAN", "DOROTEO ACOSTA EVELYN", "FLORENCIO RAMOS ANA ITZEL", "FLORES ORTIZ YARETZI", 
            "GARCIA LUGO FELIPE", "GRANILLO ORTIZ VALENTINA", "HERNANDEZ ANGELES ABRIL", "HERNANDEZ ROLDAN DIEGO", 
            "HERNÁNDEZ ALDERETE PASTOR DE JESUS", "JIMENEZ ANGELES IRVING ALBERTO", "LOPEZ ANDRADE YAFETH", 
            "MARTINEZ MONDRAGON JOSHUA CALEB", "MEDINA PELCASTRE ETHAN SANTIAGO", "MONTER LORENZO GABRIELA JAZMIN", 
            "OJEDA REYES GRETHEL DARIANA", "OMANA DE LA CRUZ ALY", "REYES SANTIAGO ALEXIS URIEL", 
            "ROBLEDO MARTINEZ THIAGO ALEJANDRO", "ROMERO GARCÍA DANIELA MICHELLE", "ROMERO GARCÍA MARÍA FERNANDA", 
            "VARGAS GUDIÑO HEIDI LEYLANI", "VAZQUEZ APOLINAR NEYLAN", "ZAYAS HERNANDEZ MIGUEL ANGEL"
        ],
        "B": [
            "AURELIO HERNANDEZ FATIMA SARAI", "AVILA JIMENEZ KARLA ABIGAIL", "BAUTISTA LARA CAMILA YAMILETH", 
            "BAUTISTA LAZARO LUNA ANGELICA", "CARDENAS CORONILLA KATERIN ZULEY", "CAYETANO GÓMEZ SANTIAGO DE JESUS", 
            "CHAVEZ HERNANDEZ LUIS JASIEL", "ESTEBAN HERNANDEZ XOCHITL YEYETZY", "GARCIA BACA MARITZA", 
            "HERNANDEZ RAMIREZ KELLY ROMINA", "HERNÁNDEZ TELLO CHRISTOPHER XAVIER", "HERNANDEZ CORONA IAN LEONEL", 
            "JUAREZ VELASCO SEBASTIAN", "LORENZO RODRIGUEZ DANIEL MARTIN", "MORELOS ORTIZ KARLA MARICELA", 
            "MORENO OLGUIN ELIAN", "MUÑOZ TORRES ARLETH GUADALUPE", "NOGUEZ MEZA LUZ CELESTE", 
            "PELCASTRE BARRERA LUIS DANIEL", "ROJAS PEREZ ABIMAEL", "SALGADO TREJO ADRIANA", 
            "SILVA MARTINEZ HUGO TADEO", "VARGAS JUAREZ ISAAC TADEO", "VELAZQUEZ RUBIO JOSHUANY PAMELA"
        ]
    },
    "Segundo": {
        "A": [
            "ALVARADO LICONA MATÍAS AGUSTÍN", "BADILLO NORIEGA EMILY NICOLE", "BARDALES ACOSTA ANA GUADALUPE", 
            "BARRAGAN NIETO MATIAS", "DIAZ LOPEZ ANGEL MAURICIO", "ENRIQUEZ GARCIA AIXA ITZAE", 
            "GARCIA HERNANDEZ DALIA TONANTZI", "GODINEZ GAYOSO EHITAN URIEL", "GUZMAN VELASCO LUZ ORIELY", 
            "HERNANDEZ PEREZ ZOE GISSELLE", "HERNANDEZ ROLDAN ZAID", "HERNÁNDEZ HERNÁNDEZ GRETEL", 
            "HERNÁNDEZ LOPEZ NAHOMI NICOLE", "JUAREZ SANCHEZ VALERY ANDREA", "LOPEZ DANIEL ALEXANDER", 
            "LUBIAN JARDINEZ JULIETH", "MENDOZA MANILLA KENYA", "MERIDA LICONA IKER YAEL", "MONTIEL PAREDES EDDIE", 
            "NAJERA SALAZAR YULISA", "NAVA GARCIA THIAGO", "RAMIREZ GARCIA GUADALUPE", "REYES FRANCO JAZIEL ARAM", 
            "RUBIO ORTIZ ERIVER GIBRAN", "SALAZAR PEREZ RENATA", "TOLENTINO CASTRO INGRID MAILEN", "VELASCO TORRES ALEXANDER"
        ],
        "B": [
            "ALVAREZ MASCOT JUANA IGNACIA", "ANGELES TOVAR ORIEL", "BALTAZAR DE JESUS ALONDRA", 
            "BAUTISTA TOLENTINO MARIA FERNANDA", "BLAS TOMAS EMANUEL", "DEL POZO VARGAS LEONARDO EMMANUELLE", 
            "FELIX GERONIMO NALLELY SARAHI", "FLORES FERRER ANGEL", "GOMEZ TRINIDAD JUVE JAYDEN", 
            "HERNANDEZ BADILLO MYRNA SUGEY", "HERNANDEZ ESCAMILLA SANTIAGO", "HERNANDEZ HERNANDEZ IVANNA LIZETH", 
            "HERNANDEZ PALAFOX LIZETH ESMERALDA", "HERNANDEZ SALINAS ALBA SOFIA", "JUAREZ HERRERA ERICK EDUARDO", 
            "LECHUGA RANGEL IDARA", "MEJIA SOTO MADISSON VALENTINA", "MONDRAGON NAVARRETE HANNA MONSERRATH", 
            "MONTIEL DORANTES MARIO", "MORELOS FERRER JAINER OBET", "OLVERA GONZALEZ JULIETH", "RAMIREZ CONTRERAS EITHAN", 
            "RESENDIZ SEGUNDO LIAM", "ROQUE GARCIA MATIAS", "SALINAS CHAVEZ ALITANA MARISOL", "TOVAR BUSTOS CARLOS ITZAE", 
            "TRINIDAD RAMIREZ KEILA ANELI"
        ]
    },
    "Tercer": {
        "A": [
            "ALVARES CASILLAS DANIA ARLETH", "BAUTISTA LORENZO FATIMA ELIZABETH", "BLAS TOMAS BENJAMIN", 
            "GRANADOS APOLINAR IKER", "HERNANDEZ CORONA CRISTIAN", "HERNANDEZ VENTURA AXEL URIEL", 
            "HERNÁNDEZ SÁNCHEZ HEIDY MAHELI", "HERNANDEZ GARCIA FRIDA GUADALUPE", "JUAREZ HERNANDEZ JULIAN ZAID", 
            "JUAREZ ORTEGA AILYN MARIA", "LEMUS ROMERO RICARDO", "LUBIAN JARDINEZ IAN", "MARTINEZ MENDEZ BRIYIT DAYANNY", 
            "MENDOZA MARTINEZ NATHAN YAEL", "MIGUEL VELAZQUEZ MAXIMILIANO", "MONTIEL HERNANDEZ YARETZI", 
            "MORENO GAYOSO SOFIA ESMERALDA", "ORTIZ GRANILLO OLIVER ALAN", "OSORIO TERAN LUIS ANTONIO", 
            "PEREZ ALVARADO ALONDRA ELIZABETH", "RODRIGUEZ VALERA KATHERINE GISEL", "ROSALES HERNANDEZ IKER SNEIDER", 
            "SAMPAYO YAÑEZ AUSTIN DILAN", "SANCHEZ HERNANDEZ JAVIER", "SANCHEZ TELLEZ ANGEL DAMIAN", 
            "SOTO GIOVANNI ALEXANDER", "VAQUEIRO CAMACHO FELIPE ALONSO", "VENTURA REYES YURIDIA", "ZAMORA LAZARO NAMINE"
        ],
        "B": [
            "ANGELES LICONA JESUS GAEL", "ANGELES OLVERA SAMANTHA JATZIRI", "ARELLANO HERNANDEZ ANGELA CAMILA", 
            "BURGOS RAMIREZ LIAN", "DAJUI SIMON SOFIA DANAE", "DEL POZO VARGAS EVAN EMMANUELLE", "ESPAÑA PALAFOX JOSHUA DIDIER", 
            "GONZÁLEZ RAMIREZ SAMANTHA DARELY", "GUTIERREZ SAN JUAN KEENETH", "HERNANDEZ HERNANDEZ AILEN HIROMI", 
            "HERNANDEZ MARTINEZ MARIA JOSE", "HERNÁNDEZ LÓPEZ IAN YAEL", "HERNÁNDEZ VENTURA MARÍA CECILIA", 
            "ISIDORO FLORES ALEXIS EDUARDO", "LARRIETA MARTINEZ LIAN JAVIER", "LOPEZ CEDRO SANTIAGO DALI", 
            "LOPEZ RAMIREZ NATALIA JATZIRI", "LORENZO RODRIGUEZ ANGEL MARTIN", "MARTINEZ CASTRO NOEL AGUSTIN", 
            "MOEDANO PEREZ GENESIS MADAI", "MORALES OLVERA DAFNE", "MORENO JACOME ALEJANDRO KENNAN", 
            "NORIEGA PEREZ LUZ ELENA", "PEÑA ISLAS LUIS ANTONIO", "PEREZ MIGUEL PERLA SOFIA", 
            "REYES SANTIAGO XIMENA DENNIS", "ROSAS HERNANDEZ IXCHEL AYLIN", "SANCHEZ AMADOR JESUS DANIEL", 
            "SANTIAGO CRUZ AXEL OLIVER", "VELASCO PORTILLO DULCE VIANEY", "ZAYAS HERNANDEZ ALESHA FERNANDA"
        ]
    },
    "Cuarto": {
        "A": [
            "ANGELES ZAYAS CAMILA", "BALTAZAR ORTA RENATA YIZEL", "BAUTISTA MERIDA SOFIA", "BAUTISTA TOVAR ALLISON YAMILET", 
            "CALVA ISLAS VALERIA YOLENI", "CHAVEZ ROA KARLA ASHLY", "CONTRERAS VELASCO DEMIAN", "CRUZ MARTINEZ ITZEL", 
            "FABELA JUAREZ ALISON", "HERNANDEZ CHAVEZ ERICK JOSUE", "HERNANDEZ HERNANDEZ JESUS JAEL", 
            "HERNANDEZ REYNAGA MONTSERRAT", "LEAL SALINAS DANIEL", "LOPEZ HERNANDEZ ANGELI", "MARTINEZ MARTINEZ SAMANTHA", 
            "MEJIA PEREZ ESPERANZA", "MENDEZ CHAVEZ IAN ABIMAEL", "MENDOZA MONTIEL EIMI SAMARA", "MORALES GONZALEZ AXEL", 
            "MURILLO CANDIDO MARIA FERNANDA", "PEÑA HERNANDEZ ALLISON BRIANA", "REYES RODRIGUEZ EMILY LIZETH", 
            "RIVERA BAEZ DANIELA", "SALAZAR CORONA JOHANA GUADALUPE", "SALVADOR PEREZ ESTEBAN", 
            "SANCHEZ HERNANDEZ EMILIANO BENJAMIN", "SANCHEZ SERRANO CANDIDO DAVID", "TOLENTINO FUENTES DENIECE JANE", 
            "VELAZQUEZ RUBIO JOSHUA NAHUM"
        ],
        "B": [
            "ARISTA HERNANDEZ SOFIA LIZETH", "BAUTISTA ANICASIO NATALIE ASHLYNN", "BAUTISTA TOLENTINO JOSE FERNANDO", 
            "CARDENAS HERNANDEZ JOSE MARIA", "CORONA ORTIZ MELANY DENNIS", "CRUZ EPITACIO EMILY GUADALUPE", 
            "DIAZ LOPEZ ANA LUCIA", "DIAZ MERIDA SOFIA", "ESPINOZA NAVARRO ANGEL NAIM", "GOMEZ ALVARADO ANGEL DAVID", 
            "GOMEZ NAJERA DAVID ELIAS", "HERNANDEZ HERNANDEZ JARET ANGEL", "LICONA COPCA GAEL", "LOPEZ ANDRADE YOSAFATH", 
            "LORENZO PEREZ EVELIN ARIANA", "MARTIN HERNANDEZ DAMIAN", "MARTINEZ ORTIZ JOSE ENRIQUE", 
            "MENDOZA SANCHEZ SEBASTIAN", "MERIDA LICONA CRISTOFER GAMALIEL", "MONTIEL DORANTES SANTIAGO", 
            "OLGUIN RODRIGUEZ ARANZA DAMARA", "RAMIREZ GARCIA JOSE FRANCISCO", "ROMERO LEMUS LAURA SOFIA", 
            "SAN JUAN ALVARADO YEUDIEL TADEO", "TERAN MARTINEZ SHERLYN YAMILETH", "TOLENTINO CASTRO ERICK", "VITE HERNANDEZ LUZ VALERIA"
        ]
    },
    "Quinto": {
        "A": [
            "ACOSTA BAUTISTA JOSE EMILIANO", "ALONSO CRUZ IRELDA", "ANGELES RIVERA KEYTLIN MAYTE", "BADILLO RODRIGUEZ ANYELIN", 
            "BALTAZAR DE JESUS MIGUEL ANGEL", "BAUTISTA TOVAR YAEL", "CALVA MEDINA IKER", "CATALAN RAMOS ELIZABETH", 
            "DAJUI SIMON FERNANDA LINNET", "ESCAMILLA HERNANDEZ ALEXIS", "FRANCO CORONA ALAN", "GALVAN RODRIGUEZ ANGEL GAEL", 
            "HERNANDEZ CRUZ ALFREDO", "HERNANDEZ MENDOZA MARLENY AYLIN", "HERNANDEZ SANCHEZ ASHLEY CHANTAL", 
            "JUAREZ DIAZ DILAN MOISES", "JUAREZ HERRERA ELIZABETH", "MENDEZ CHAVEZ HEIDI JOHANA", "MEZA TORRES AURELIO", 
            "MONROY CERECEDO YARETZI MARIEL", "MORENO NAVA ESTEFANIA", "MUÑOZ BAUTISTA LUIS ALBERTO", "NEGRETE ORTIZ MARISOL", 
            "PEÑA ISLAS VANESSA", "PEREZ OSORIO JULIO CESAR", "PORTES REYES ALONDRA ANALY", "RICO DUARTE ANDREA", 
            "RODRIGUEZ VALERA WENDY SOLANGE", "SALAZAR PEREZ ANGEL SANTIAGO"
        ],
        "B": [
            "ALMARAS PEREZ JOSE CARLOS", "ANGELES MENDOZA ALAN GIOVANNI", "ANGELES MENDOZA KARINA AYELEN", "BAUTISTA SOLIS KEVIN MATEO", 
            "BUSTAMANTE RODRIGUEZ ODALYS VALENTINA", "CAMPERO NAVA ASHLEY ZOE", "CONTRERAS LICONA FERNANDO", "DE JESUS CORTEZ DANIELA", 
            "GOMEZ SOLIS XIMENA", "GRANILLO JUSTO IRVING ALEJANDRO", "HERNANDEZ CHAVEZ IKER ANTONIO", "HERNANDEZ HERNANDEZ JUAN DANIEL", 
            "HERNANDEZ RAMIREZ SOFIA RENATA", "HERNANDEZ CRUZ CAMILA", "JUAREZ HERNANDEZ ANELY", "JUAREZ MORENO ANGEL GABRIEL", 
            "JUAREZ SANCHEZ ALLISON ANALUISA", "MENDEZ OLIVARES ANGEL GAEL", "NAVA GARCIA MATEO", "NOGUEZ MEZA LINDA RUBY", 
            "PACHECO MONROY ALEXANDER", "PALACIOS REYES MATEO RAFAEL", "SALAZAR CORONA RAFAEL", "SALINAS SEGUNDO ALEXA NAHOMI", 
            "SANCHEZ SERRANO DULCE CAMILA", "SIERRA REYNA TAILY YAQUELIN", "VEGA MARTINEZ ANA SOFIA", "VELAZQUEZ GUZMAN PERLA IVET"
        ]
    },
    "Sexto": {
        "A": [
            "ALVARADO LICONA SANTIAGO DAMIAN", "BALTAZAR VERA HANNA CAMILA", "BAUTISTA MENDOZA AXEL DANIEL", 
            "BAUTISTA BAUTISTA ANGELA CAROLINA", "CAMARENA AVILA EVELYN", "CASTRO ALFARO KENNEDY YAMILETH", 
            "CRUZ BACA JESUS", "DE LA CRUZ FLORES MELANY", "DEL POZO VARGAS SANTINO EMMANUELLE", 
            "DOROTEO ACOSTA LEONARDO", "ESCAMILLA PLATA UZZIEL", "GALVAN BAUTISTA DANIEL", 
            "GARCIA LUGO ANA BERENISE", "HERNANDEZ HERNANDEZ JOHAN ALEJANDRO", "HERNANDEZ JUAREZ VICTOR GABRIEL", 
            "HERNANDEZ LOPEZ DANA LORETO", "HERNANDEZ OSORIO MATIAS DAMIAN", "HERNANDEZ VENTURA SANTIAGO", 
            "HUESCA GUZMAN JOSSELIN MABEL", "ITURBE LOPEZ LYA SOFIA", "JIMENEZ ROMERO JOSE EMILIANO", 
            "LEAL SALINAS MARIA FERNANDA", "LOPEZ VARGAS GUSTAVO", "MARTINEZ CHAVEZ ALLISON NAHOMI", 
            "MENDOZA MANILLA KEYLA MAYTE", "MIRANDA MEJIA ALEXIS GABRIEL", "MONDRAGON PEREZ MIA ZOEL", 
            "MONTES TORRES DARELL GAEL", "RAMIREZ RODRIGUEZ EDGAR YAIR", "REYES ROMERO SOFIA", 
            "ROBLEDO MARTINEZ JOSUE YAEL", "VELASCO PORTILLO XIMENA BERENICE"
        ],
        "B": [
            "ANGELES HERNANDEZ JOSSUE MAXIMINO", "BAUTISTA ANICASIO OLIVER DANIK", "BAUTISTA TORRES DIANA", 
            "BAUTISTA LORENZO ANTHONY NAIM", "CARDENAS HERNANDEZ PEDRO ABEL", "CONTRERAS VELASCO SOFIA", 
            "FRANCO CORONA HECTOR VALENTIN", "GARCIA BUSTOS SAMANTHA", "GONZALEZ YAÑEZ ESMERALDA MARGARITA", 
            "HERNADEZ BADILLO ANGEL GABRIEL", "HERNANDEZ CAMARENA DIANA GUADALUPE", "HERNANDEZ CORONA ANGEL EMMANUEL", 
            "HERNANDEZ FRAGOSO UZIEL", "HERNANDEZ HERNANDEZ JOHAN ALEJANDRO", "HERNÁNDEZ OLVERA SOFIA JATZIRI", 
            "LARRIETA MARTINEZ LEONARDO DANIEL", "MARTINEZ ESCAMILLA EIDER EMANUEL", "MEJIA SOTO AXEL GAEL", 
            "MONTIEL HERNANDEZ JESUS ARTURO", "MORENO BAUTISTA MAYLIN", "MORGADO SANTIAGO DILAN ALEXIS", 
            "MOTA VAZQUEZ ALYSSON DAYANNA", "PEREZ ALVARADO CAMILA ISABEL", "RICO DUARTE GABRIEL ENRIQUE", 
            "RIVERA BAEZ MAXIMILIANO", "RODRIGUEZ PEREZ ALEXIS DE JESUS", "ROSALES RAMIREZ KENDRA GUADALUPE", 
            "SAUCEDO MENDOZA ABRIL SOFIA", "VENTURA HERNANDEZ LUIS ALBERTO", "VITE HERNANDEZ ANA PAULA"
        ]
    }
};